import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Slider from '../components/Slider'
import {SliderData} from '../components/SliderData'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Photography</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Hero message="There is so much more to discover"/>
    <Slider slides={SliderData} />
    </div>
  )
}
